# Site settings
name: Celso Cercado Jr.
title: Celso Cercado Jr. Portfolio
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://brittanychiang.com/
baseurl: ""
email: celsocercado@gmail.com
cover: https://brittanychiang.com/img/og.png
logo: https://brittanychiang.com/img/emojis/technologist.png
resume: https://brittanychiang.com/resume.pdf
social:
  - title: email
    url: mailto:celsocercado@gmail.com
  - title: codepen
    url:
  - title: github
    url: https://github.com/Celso-Cercado-Jr
  - title: linkedin
    url:

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
